//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maintenance.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=LogAccess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_SearchDates_Result> sp_SearchDates(Nullable<System.DateTime> dateone, Nullable<System.DateTime> datetwo)
        {
            var dateoneParameter = dateone.HasValue ?
                new ObjectParameter("dateone", dateone) :
                new ObjectParameter("dateone", typeof(System.DateTime));
    
            var datetwoParameter = datetwo.HasValue ?
                new ObjectParameter("datetwo", datetwo) :
                new ObjectParameter("datetwo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchDates_Result>("sp_SearchDates", dateoneParameter, datetwoParameter);
        }
    }
}
