// <auto-generated />
namespace Maintenance.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbchangetofksetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbchangetofksetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201711301835233_db change to fk setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
