// <auto-generated />
namespace Maintenance.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class close2production : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(close2production));
        
        string IMigrationMetadata.Id
        {
            get { return "201710102132282_close2production"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
